#!/bin/bash

echo '::  docker-machine restart'
docker-machine restart

echo '::  eval $(docker-machine env)'
eval $(docker-machine env)

echo '::  docker-compose up -d'
docker-compose up -d

echo '::  Type "eval $(docker-machine env)" if the movement is bad.'
