#!/bin/bash

echo '::if [ `docker-machine status |fgrep Stopped` ];'
if [ `docker-machine status |fgrep Stopped` ]; then
    echo '::docker-machine start'
    docker-machine start
    echo '::eval $(docker-machine env)'
    eval $(docker-machine env)
fi

echo '::docker-compose up -d'
docker-compose up -d
