#!/bin/bash

echo '::docker-machine restart'
docker-machine restart

echo '::docker-machine env'
docker-machine env > ./docker-machine-env.sh
source ./docker-machine-env.sh
rm ./docker-machine-env.sh

echo '::docker-compose up -d'
docker-compose up -d
