#!/bin/bash

echo '::if [ `docker-machine status |fgrep Stopped` ];'
if [ `docker-machine status |fgrep Stopped` ]; then
    echo '::docker-machine start'
    docker-machine start

    echo '::docker-machine env'
    docker-machine env > ./docker-machine-env.sh
    source ./docker-machine-env.sh
    rm ./docker-machine-env.sh
    #eval $(docker-machine env)
fi

echo '::docker-compose up -d'
docker-compose up -d
